baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "CoruDocs Technical Knowledge (by Felipe)"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/frodriguezmtnz/corudocs-technical-test/edit/main/content/"
  description = "Documentation site dev CorunetDocs (by Felipe)"
  author = "Felipe Rodriguez"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = true
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = " | "

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation site dev CorunetDocs (by Felipe)"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"